ALTER TABLE loans ALTER COLUMN borrowed_at DROP NOT NULL;
ALTER TABLE loans ALTER COLUMN due_at DROP NOT NULL;
ALTER TABLE loans ADD COLUMN reserved_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE loans ADD COLUMN reserved_until TIMESTAMP WITH TIME ZONE;
ALTER TABLE loans ADD COLUMN released_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE users ADD COLUMN borrow_columns VARCHAR(100);
