spring:
  application:
    name: data4life
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/data4life}
    username: ${DB_USER:data4life}
    password: ${DB_PASSWORD:data4life}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true

server:
  port: ${SERVER_PORT:8080}

management:
  endpoints:
    web:
      exposure:
        include: health
